require:
  - rubocop-performance
  - rubocop-thread_safety

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - bin/**/*
    - implementations/**/*
    - results/**/*
    - vendor/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/WordArray:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - benchmarks/**/*
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 30
  Exclude:
    - benchmarks/**/*
